#!/usr/bin/env node
// Reproducible offline Befund bundle. No patient/example data or external runtime.
import assert from 'node:assert/strict';
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
const repo=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const modules=process.env.ONTSEQ_WEB_NODE_MODULES ? resolve(process.env.ONTSEQ_WEB_NODE_MODULES) : join(repo,'web/node_modules');
const lock=JSON.parse(await readFile(join(repo,'web/package-lock.json'),'utf8'));
const names=['react','react-dom','scheduler'];
for(const name of [...names,'esbuild']) {
 const installed=JSON.parse(await readFile(join(modules,name,'package.json'),'utf8'));
 assert.equal(installed.version,lock.packages[`node_modules/${name}`].version);
}
const {build}=await import(pathToFileURL(join(modules,'esbuild/lib/main.js')).href);
const output=await build({entryPoints:[join(repo,'web/src/befund/main.jsx')],bundle:true,write:false,outdir:join(repo,'web/.befund-unused'),format:'iife',platform:'browser',target:['chrome100','edge100','firefox100','safari15.4'],jsx:'automatic',define:{'process.env.NODE_ENV':'"production"'},minify:true,sourcemap:false,legalComments:'inline',charset:'utf8',alias:Object.fromEntries(names.map(name=>[name,join(modules,name)])),nodePaths:[modules],logLevel:'warning'});
assert.equal(output.outputFiles.length,2);
const js=output.outputFiles.find(file=>file.path.endsWith('.js')).text;
const css=output.outputFiles.find(file=>file.path.endsWith('.css')).text;
assert.doesNotMatch(css,/@import|url\s*\(/i);
const licenses=await Promise.all(names.map(async name=>`${name}@${lock.packages[`node_modules/${name}`].version}\n${await readFile(join(modules,name,'LICENSE'),'utf8')}`));
const escape=value=>value.replace(/<\/script/gi,'<\\/script').replace(/<\/style/gi,'<\\/style');
const html=`<!-- Generated by scripts/build_befund.mjs; no run data. -->\n<style>${escape(css)}</style><script>${escape(js)}</script><script type="text/plain" id="ontseq-befund-notices">${escape(licenses.join('\n'))}</script>\n`;
const target=join(repo,'src/ontseq_platform/report_bundle.html');
if(process.argv.includes('--check')) assert.equal(await readFile(target,'utf8'),html,'Befund bundle is stale; run npm run build:befund');
else await writeFile(target,html);
console.log(`Befund bundle ${process.argv.includes('--check')?'verified':'built'} (${Buffer.byteLength(html)} bytes)`);
